package:
  format-version: "1.0.0"
  name: "core"
  type: "api"
  status: "production"
  required: false
  version: "v3.14.0-E1"

  dependencies:
    - name: "bsp"
      type: "package"
      version: "v3.21.0-E1"
    - name: "csp"
      type: "package"
      version: "v3.20.0-E1"
    - name: "FreeRTOS-Kernel"
      type: "package"
      version: "V11.1.0"
    - name: "littlefs"
      type: "package"
      version: "v2.5.1"
    - name: "filex"
      type: "package"
      version: "v6.2.1_rel"
