package:
  format-version: "1.0.0"
  name: "core"
  type: "api"
  status: "production"
  required: false
  version: "v3.14.2"

  dependencies:
    - name: "bsp"
      type: "package"
      version: "v3.22.0"
    - name: "csp"
      type: "package"
      version: "v3.21.0"
    - name: "FreeRTOS-Kernel"
      type: "package"
      version: "V11.1.0"
